
baseURL = "" 
# "https://marcombes-solutions.github.io/montboudif/public/"
title = "Montboudif"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = "true"

[params]
    description = "Site de la commune de Montboudif"
    author = "Marcombes Solutions 2020"
    email = "contact@marcombes.fr"
    address = "15190 Montboudif"

[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
      lang = "en"
      share = "Share"
      links = "Links"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 0
      [[languages.en.menu.main]]
        identifier = "commune"
        name = "Commune"
        url = "commune/p"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "visit"
        name = "Visit"
        url = "visiter/p"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "local"
        name = "Local life"
        url = "local/p"
        weight = 30
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "#contact"
        weight = 40
  [languages.fr]
    weight = 2
    [languages.fr.params]
      lang = "fr"
      share = "Partager"
      links = "Liens"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 0
      [[languages.fr.menu.main]]
        identifier = "commune"
        name = "Commune"
        url = "commune/p"
        weight = 10
      [[languages.fr.menu.main]]
        identifier = "visit"
        name = "Visiter"
        url = "visiter/p"
        weight = 20
      [[languages.fr.menu.main]]
        identifier = "local"
        name = "Vie locale"
        url = "local/p"
        weight = 30
      [[languages.fr.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "#contact"
        weight = 40

[menu]
  